[package]
name = "pymathutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pymathutils"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"

math_utils = {path = "../math_utils"}
