[package]
name = "stormbird_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
bincode = "1.3.3"
clap = { version = "4.5.23", features = ["derive"] }

stormbird = { path = "../../stormbird" }
