[package]
name = "cpp_actuator_line"
version = "0.5.2"
edition = "2021"

[lib]
crate-type = ["staticlib"] 

[dependencies]
cxx = "1.0"

stormbird = {path = "../../stormbird"}
math_utils = {path = "../../math_utils"}
