
class Simulation:
    def __init__(self, input_string: str) -> None: ...
    def get_freestream_velocity_points(self) -> list[list[float]]: ...
    def set_local_wing_angles(self, angles: list[float]): ...
    def do_step(
        self, 
        time: float, 
        time_step: float, 
        freestream_velocity: list[list[float]]
    ) -> None: ...