"""Type stubs for pystormbird.line_force_model."""


class LineForceModel:
    def __init__(self, json_string: str) -> None: ...

    def circulation_strength(
        self, angles_of_attack: list[float], velocity: list[list[float]]
    ) -> list[float]: ...

    def angles_of_attack(self, velocity: list[list[float]]) -> list[float]: ...

    @property
    def ctrl_points(self) -> list[list[float]]: ...
    @property
    def wing_indices(self) -> list[list[int]]: ...
    @property
    def ctrl_point_spanwise_distance_non_dimensional(self) -> list[float]: ...
