"""Type stubs for pystormbird.section_models."""

from typing import Any


class SectionModel:
    def __init__(self, setup_string: str) -> None: ...
    @property
    def __dict__(self) -> Any: ...


class Foil:
    def __init__(self, input_string: str) -> None: ...

    def lift_coefficient(self, angle_of_attack: float) -> float: ...
    def drag_coefficient(self, angle_of_attack: float) -> float: ...
    def as_section_model(self) -> SectionModel: ...

    @property
    def cl_zero_angle(self) -> float: ...
    @cl_zero_angle.setter
    def cl_zero_angle(self, value: float) -> None: ...

    @property
    def cl_initial_slope(self) -> float: ...
    @cl_initial_slope.setter
    def cl_initial_slope(self, value: float) -> None: ...

    @property
    def cl_high_order_factor_positive(self) -> float: ...
    @cl_high_order_factor_positive.setter
    def cl_high_order_factor_positive(self, value: float) -> None: ...

    @property
    def cl_high_order_factor_negative(self) -> float: ...
    @cl_high_order_factor_negative.setter
    def cl_high_order_factor_negative(self, value: float) -> None: ...

    @property
    def cl_high_order_power(self) -> float: ...
    @cl_high_order_power.setter
    def cl_high_order_power(self, value: float) -> None: ...

    @property
    def cl_max_after_stall(self) -> float: ...
    @cl_max_after_stall.setter
    def cl_max_after_stall(self, value: float) -> None: ...

    @property
    def cd_min(self) -> float: ...
    @cd_min.setter
    def cd_min(self, value: float) -> None: ...

    @property
    def angle_cd_min(self) -> float: ...
    @angle_cd_min.setter
    def angle_cd_min(self, value: float) -> None: ...

    @property
    def cd_second_order_factor(self) -> float: ...
    @cd_second_order_factor.setter
    def cd_second_order_factor(self, value: float) -> None: ...

    @property
    def cd_max_after_stall(self) -> float: ...
    @cd_max_after_stall.setter
    def cd_max_after_stall(self, value: float) -> None: ...

    @property
    def cd_power_after_stall(self) -> float: ...
    @cd_power_after_stall.setter
    def cd_power_after_stall(self, value: float) -> None: ...

    @property
    def mean_positive_stall_angle(self) -> float: ...
    @mean_positive_stall_angle.setter
    def mean_positive_stall_angle(self, value: float) -> None: ...

    @property
    def mean_negative_stall_angle(self) -> float: ...
    @mean_negative_stall_angle.setter
    def mean_negative_stall_angle(self, value: float) -> None: ...

    @property
    def stall_range(self) -> float: ...
    @stall_range.setter
    def stall_range(self, value: float) -> None: ...

    @property
    def __dict__(self) -> Any: ...


class VaryingFoil:
    def __init__(self, input_str: str) -> None: ...

    def set_internal_state(self, internal_state: float) -> None: ...
    def lift_coefficient(self, angle_of_attack: float) -> float: ...
    def drag_coefficient(self, angle_of_attack: float) -> float: ...

    @property
    def __dict__(self) -> Any: ...


class RotatingCylinder:
    def __init__(self, input_string: str) -> None: ...

    def spin_ratio(self, diameter: float, velocity: float) -> float: ...
    def lift_coefficient_from_spin_ratio(self, spin_ratio: float) -> float: ...
    def lift_coefficient(self, diameter: float, velocity: float) -> float: ...
    def drag_coefficient(self, diameter: float, velocity: float) -> float: ...
    def drag_coefficient_from_spin_ratio(self, spin_ratio: float) -> float: ...
    def as_section_model(self) -> SectionModel: ...
