[package]
name = "tabulated_motion"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
stormath = { path = "../../../../stormath"}
csv = "1.3.1"
fmu_from_struct = "0.1.2"
serde = { version = "1.0.215", features = ["derive"] }
