[package]
name = "sail_controller"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fmu_from_struct = { version = "0.1.1" }

stormbird = { path = "../../stormbird"}
math_utils = { path = "../../math_utils"}
serde_json = "1.0.128"