import xml.etree.ElementTree as ET

import argparse

if __name__ == '__main__':
    '''
    This script changes the weather parameters in a simulation file generated by ShipX.
    '''

    parser = argparse.ArgumentParser(description='Modify weather in simulation.')
    parser.add_argument('--wind-speed', type=float, default=10.0, help='Wind speed in m/s.')
    parser.add_argument('--wind-direction', type=float, default=0.0, help='Wind direction in degrees.')
    parser.add_argument('--wave-height', type=float, default=0.0, help='Wave height in m.')
    parser.add_argument('--wave-direction', type=float | None, default=None, help='Wave direction in degrees. Is equal to the wind direction if not specified.')
    parser.add_argument('--wave-period', type=float, default=10.0, help='Wave period in s.')

    args = parser.parse_args()

    namespace = "http://opensimulationplatform.com/MSMI/OSPSystemStructure"
    
    ET.register_namespace('', namespace)

    tree = ET.parse('OspSystemStructure_from_ship_x.xml')

    # get root element
    root = tree.getroot()

    # get simulators and connections
    simulators  = root.find('Simulators', namespaces={'': namespace})

    print(simulators)

    tree.write('OspSystemStructure_with_modified_weather.xml', encoding='utf-8', xml_declaration=True)


